import"./assets/support-6f1847bf.js";import{a as b}from"./assets/vendor-26fe51b3.js";const y="https://books-backend.p.goit.global/";function E(e){if(!e.data)throw new Error("Invalid response format");return e.data}function C(e){throw e.response?new Error(`Request failed with status ${e.response.status}`):e.request?new Error("No response received from the server"):new Error(`Error setting up the request: ${e.message}`)}async function L(){try{const e=await b.get(`${y}books/category-list`);return E(e)}catch(e){C(e)}}async function k(){try{const e=await b.get(`${y}books/top-books`);return E(e)}catch(e){C(e)}}async function $(e){try{const t=await b.get(`${y}books/category?category=${e}`);return E(t)}catch(t){C(t)}}const f=document.querySelector(".all-categories"),T=document.querySelector(".book-category-list"),u=document.querySelector(".Books-best-sellers-text"),d=document.querySelector(".active-all-categories");d.classList.remove("inactive-all-categories");L().then(e=>{e.sort((t,n)=>t.list_name>n.list_name?1:-1).map(t=>{const{list_name:n}=t;return f.insertAdjacentHTML("beforeend",`<li><a class="list-category"href="">${n}</a></li>`)}).join("")}).catch(e=>console.log(e));f.addEventListener("click",x);function x(e){e.preventDefault(),console.log(e.target.textContent);const t=e.target.textContent;if(t==="All categories"){d.classList.remove("inactive-all-categories"),d.classList.add("active-all-categories"),u.innerHTML="Best Sellers";const n=" Books";let a=document.createElement("span");a.classList.add("Books-best-sellers-text-span"),a.textContent=n,u.appendChild(a),k().then(c=>{const o=document.querySelector(".book-category-list");c.forEach(l=>{const s=document.createElement("h3");s.textContent=`${l.list_name}`.toUpperCase(),s.className="bs-h3";const r=document.createElement("ul");r.className="bs-book-list",l.books.forEach(m=>{const g=document.createElement("li");g.className="bs-book-item",g.innerHTML=`
          <img class="bs-book-image" src="${m.book_image}" alt="${m.title}"" />
          <p class="title-book">${m.title}</p>
          <p class="author-book">${m.author}</p>
        `,r.appendChild(g)}),o.appendChild(s),o.appendChild(r);const i=document.createElement("button");i.type="button",i.classList.add("bs-buttom");const p=document.createElement("span");p.textContent="See More",p.classList.add("bs-buttom-name"),i.appendChild(p),o.appendChild(i)})}).catch(c=>console.error("Error fetching data:",c))}else{d.classList.remove("active-all-categories"),d.classList.add("inactive-all-categories");const a=t.split(" ").slice(0,-1),c=t.split(" ").pop();u.innerHTML=a.join(" ");let o=document.createElement("span");o.classList.add("Books-best-sellers-text-span"),o.textContent=` ${c}`,u.appendChild(o)}t&&$(t).then(n=>{const a=n.map(({book_image:c,title:o,author:l,_id:s})=>`<li id="${s}" class="bs-book-item">
      <img class="bs-book-image" src="${c}" alt="${o}" />
      <p class="title-book">${o}</p>
      <p class="author-book">${l}</p>
    </li>`).join("");return T.innerHTML=a}).catch(n=>console.log(n))}function B(e){const t=document.getElementById("myModal"),n=document.getElementById("modalImage"),a=document.getElementById("modalTitle"),c=document.getElementById("modalAuthor"),o=document.getElementById("modalDescription");document.getElementById("modal-button"),document.getElementById("bs-book-item"),t.style.display="block",n.src=`${e.image}`,a.textContent=`${e.title}`,c.textContent=`${e.author}`,o.textContent=`${e.description}`;const l=document.getElementsByClassName("close")[0];l.onclick=function(){t.style.display="none"},window.onclick=function(s){s.target===t&&(t.style.display="none")}}k().then(e=>{const t=document.querySelector(".book-category-list");e.forEach(n=>{const a=document.createElement("h3");a.textContent=`${n.list_name}`.toUpperCase(),a.className="bs-h3";const c=document.createElement("ul");c.className="bs-book-list",n.books.forEach(s=>{const r=document.createElement("li");r.className="bs-book-item";const i={title:s.title,author:s.author,image:s.book_image,description:s.description};r.innerHTML=`
          <img src="${s.book_image}" alt="${s.title}" />
          <p class="title-book">${s.title}</p>
          <p class="author-book">${s.author}</p>
        `,c.appendChild(r),r.addEventListener("click",()=>{B(i)})}),t.appendChild(a),t.appendChild(c);const o=document.createElement("button");o.type="button",o.classList.add("bs-buttom");const l=document.createElement("span");l.textContent="See More",l.classList.add("bs-buttom-name"),o.appendChild(l),t.appendChild(o)})}).catch(e=>console.error("Error fetching data:",e));const h=document.querySelector(".scroll-btn");window.onscroll=function(){v()};function v(){document.body.scrollTop>100||document.documentElement.scrollTop>100?h.style.display="block":h.style.display="none"}h.addEventListener("click",function(){w()});function w(){document.body.scrollTop=0,document.documentElement.scrollTop=0}
//# sourceMappingURL=commonHelpers.js.map
