import"./assets/support-c834f1e5.js";import{a as d}from"./assets/vendor-26fe51b3.js";const m="https://books-backend.p.goit.global/";function u(e){if(!e.data)throw new Error("Invalid response format");return e.data}function p(e){throw e.response?new Error(`Request failed with status ${e.response.status}`):e.request?new Error("No response received from the server"):new Error(`Error setting up the request: ${e.message}`)}async function g(){try{const e=await d.get(`${m}books/category-list`);return u(e)}catch(e){p(e)}}async function b(){try{const e=await d.get(`${m}books/top-books`);return u(e)}catch(e){p(e)}}async function y(e){try{const t=await d.get(`${m}books/category?category=${e}`);return u(t)}catch(t){p(t)}}const h=document.querySelector(".all-categories"),f=document.querySelector(".book-category-list");g().then(e=>{e.sort((t,o)=>t.list_name>o.list_name?1:-1).map(t=>{const{list_name:o}=t;return h.insertAdjacentHTML("beforeend",`<li ><a class="list-category" href="">${o}</a></li>`)}).join("")}).catch(e=>console.log(e));h.addEventListener("click",E);function E(e){e.preventDefault();const t=e.target.textContent;t&&y(t).then(o=>{console.log(o);const r=o.map(({book_image:c,title:n,author:a,_id:s})=>`<div id="${s}">
          <img src="${c}" alt="${n}" width="180px" height="256px" />
          <p>${n}</p>
          <p>${a}</p>
        </div>`).join("");return f.innerHTML=r}).catch(o=>console.log(o))}b().then(e=>{const t=document.querySelector(".book-category-list");e.forEach(o=>{const r=document.createElement("h3");r.textContent=`${o.list_name}`.toUpperCase(),r.className="bs-h3";const c=document.createElement("ul");c.className="bs-book-list",o.books.forEach(s=>{const l=document.createElement("li");l.className="bs-book-item",l.innerHTML=`
          <img class="bs-book-image" src="${s.book_image}" alt="${s.title}"" />
          <p class="title-book">${s.title}</p>
          <p class="author-book">${s.author}</p>
        `,c.appendChild(l)}),t.appendChild(r),t.appendChild(c);const n=document.createElement("button");n.type="button",n.classList.add("bs-buttom");const a=document.createElement("span");a.textContent="See More",a.classList.add("bs-buttom-name"),n.appendChild(a),t.appendChild(n)})}).catch(e=>console.error("Error fetching data:",e));const i=document.querySelector(".scroll-btn");window.onscroll=function(){k()};function k(){document.body.scrollTop>100||document.documentElement.scrollTop>100?i.style.display="block":i.style.display="none"}i.addEventListener("click",function(){$()});function $(){document.body.scrollTop=0,document.documentElement.scrollTop=0}
//# sourceMappingURL=commonHelpers.js.map
